debug: true

messenger-type: redis

group: paradisia

plugin-groups:
  itemsAdder: paradisia

server-name: changeme

redis:
  host: localhost
  port: 6380
  db: 0
  timeout: 60
  password: password1

mqtt:
  broker-uri: tcp://localhost:1883
  keep-alive: 30
  username: mqttuser
  password: password1